### ISSUE TITLE
Bad link in paper

### ISSUE THREAD

**Issue by barryrowlingson** [mobs-lab/mixing-patterns#1]
This 

https://www.mobs-lab.org/uploads/6/7/8/7/6787877/main_arxiv.pdf

says:

"As a service to the community,  a database containing the inferred setting-specific matrices aswell as the overall contact matrices for all locations (and countries) is available on the dedicatedwebsite:  https://github.com/mobs-lab/mixing-patterns.   Python  codes  to  work  with  the  contactmatrices and examples of how to use them in age-structured compartmental models are availableon the same website as well."

but there's nothing here.

**Comment by lejarx** [comment]
Hi author, could you please update the repo with code and data? Thanks!

**Comment by barryrowlingson** [comment]
From the author on twitter: https://twitter.com/alexvespi/status/1234817905520451585?s=20
"""
Paper will go on the arxiv soon, but is not peer-reviewed yet. 
We will upload data as soon as the paper is up on the arxiv and there is a stable link.
"""

**Comment by philarevalo** [comment]
Hello! Also wondering when the data will be available given that the paper is now on arxiv. Thanks!

**Comment by sloboy** [comment]
Any update on data and code availability?  This would help enormously with a project I am on.

**Comment by ekostenll** [comment]
Yes, any ETA on data availability?  It seems like the paper has been posted for a while, and would be very nice to be able to use your matrices...
