### ISSUE TITLE
A CSV file is not comma separated

### ISSUE THREAD

**Issue by jfunction** [mobs-lab/mixing-patterns#12]
The file [Canada_country_level_F_school_setting_85.csv](https://github.com/mobs-lab/mixing-patterns/blob/d52409fb875c08a4a34004b87175afefeddec929/data/contact_matrices/Canada_country_level_F_school_setting_85.csv) does not contain commas and is instead separated by spaces. I'm not sure why but it seems it's just this one file. 

I noticed there are zeros so I thought maybe the issue occurred because the population for those age groups was zero and maybe there is a singularity there but found other matrices with many zeros, eg [Australia_subnational_Northern_Territory_F_work_setting_85.csv](https://github.com/mobs-lab/mixing-patterns/blob/d52409fb875c08a4a34004b87175afefeddec929/data/contact_matrices/Australia_subnational_Northern_Territory_F_work_setting_85.csv) and [Ireland_country_level_F_household_setting_85.csv](https://github.com/mobs-lab/mixing-patterns/blob/d52409fb875c08a4a34004b87175afefeddec929/data/contact_matrices/Ireland_country_level_F_household_setting_85.csv)

**Comment by dinacmistry** [comment]
Hi, thanks for the heads up about the comma delimiter in that file. Will fix that issue.

As for the zeros in some of the files - that actually makes sense. So if you think about the work setting file example, there are blocks of consecutive rows and columns where the value is zero. What this is telling you is that in some places, there are age groups that are not working and thus shouldn't show up as having contact with other age groups in the work layer in the role of employees (perhaps they show up in some customer/public facing work settings, but that is what we use the community layer for). In the Northern Territory example, we're seeing that employment records show no one under 16 years old working and some of the older ages are also reported as not working.

**Comment by jfunction** [comment]
Thanks for the fix. 

I get that about the zeros, though when I looked at it again I wondered why there are zeros in [Ireland_country_level_F_household_setting_85.csv](https://github.com/mobs-lab/mixing-patterns/blob/d52409fb875c08a4a34004b87175afefeddec929/data/contact_matrices/Ireland_country_level_F_household_setting_85.csv) for example - it looks like 46 year olds have no interactions with children under the age of 5 in the household setting?

~And surely there are occupations like medical doctors who would have contacts with younger age groups, so you'd expect to see only close to zero contacts with younger ages? Or should it be interpreted as workers at work interacting with other workers at work?~ Reread your comment, I see this is the community layer now.

Also things like [Australia_subnational_Northern_Territory_F_work_setting_85.csv](https://github.com/mobs-lab/mixing-patterns/blob/d52409fb875c08a4a34004b87175afefeddec929/data/contact_matrices/Australia_subnational_Northern_Territory_F_work_setting_85.csv) where the ages 77 to 79 have rows/cols of zeros but older ages seem to be represented, and 76 year olds have 0 contacts with other 76 year olds in that setting. It is confusing to me why that would be the case. Maybe it's just what the employment record data said?

I was trying to understand the technique from the Supplementary Material but I guess I need to read it a few more times. It looked like you created a synthetic population with people in households/workplaces/schools and used that to construct the matrices? So maybe no 46 year olds were in a house with under 5 year olds by chance?  Or is this more likely a reflection of the data itself?
